SERIAL:
  PORT: /dev/ttyUSB0

FLUENT:
  HOST: proxy.green-rabbit.net

  DATA:
    TAG: hems
    LABEL: sharp
    FIELD: power

INFLUXDB:
  URL: http://proxy.green-rabbit.net:8086
  TOKEN: strBCB9segqccgxsR5Xe_9RnCqkBFYX9aOKvxVR4lr3iLEb7HXuGqsN40YU6DIb6TZm9bvKLW5OWQS7sB8AQbQ==
  ORG: home
  BUCKET: sensor

LIVENESS:
  FILE: /dev/shm/healthz
